project_id = "bzooojifrzwdyvbuyoel"

[functions.verify-topup]
verify_jwt = false

[functions.create-topup]
verify_jwt = false

[functions.security-honeypot]
verify_jwt = false

[functions.rate-limit-check]
verify_jwt = false