project_id = "abpbafflztnmyixumaqi"

[functions.create-guest-checkout]
verify_jwt = false

[functions.verify-guest-payment]
verify_jwt = false

[functions.create-guest-razorpay]
verify_jwt = false

[functions.verify-guest-razorpay]
verify_jwt = false

[functions.create-guest-manual-order]
verify_jwt = false