project_id = "bzooojifrzwdyvbuyoel"

[functions.verify-topup]
verify_jwt = false

[functions.create-topup]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-validate-session]
verify_jwt = false

[functions.admin-fetch-data]
verify_jwt = false